// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Ow1H08ANukql-npkghFf_v4ZvaDO-nc',
    appId: '1:478227061034:web:7408a1d17f93cf62dba653',
    messagingSenderId: '478227061034',
    projectId: 'flutterfirebaseeducated-9991e',
    authDomain: 'flutterfirebaseeducated-9991e.firebaseapp.com',
    storageBucket: 'flutterfirebaseeducated-9991e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuTQj8Ez05P9PdTLXXOz4ylCkz_0rpG-g',
    appId: '1:478227061034:android:63fff3afd0650f20dba653',
    messagingSenderId: '478227061034',
    projectId: 'flutterfirebaseeducated-9991e',
    storageBucket: 'flutterfirebaseeducated-9991e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSkB6A8WemhtCwo7x6t2rZ3flfhTtZUhk',
    appId: '1:478227061034:ios:9bc6152d81a40b45dba653',
    messagingSenderId: '478227061034',
    projectId: 'flutterfirebaseeducated-9991e',
    storageBucket: 'flutterfirebaseeducated-9991e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
